---

- name: Setup prerequisite dnf packages
  dnf:
    name:
      - gcc
      - httpd-devel
      - libcurl-devel
      - libtool
      - make
      - openssl-devel
      - pcre-devel
      - php
      - redhat-rpm-config
    state: present

- name: Check if CAS client is already installed
  stat:
    path: /etc/httpd/modules/mod_auth_cas.so
  register: cas_client

- name: Check if cas client zip file exists
  stat:
    path: "/tmp/cas-client.zip"
  register: cas_client_zip

# Only download source zip if it isn't already downloaded
# and the CAS client isn't already installed
- name: Download source zip when it doesn't already exist
  get_url:
    url: https://github.com/apereo/mod_auth_cas/archive/master.zip
    dest: /tmp/cas-client.zip
    mode: 0600
  when: cas_client_zip.stat.exists == False and cas_client.stat.exists == False

# Only unpack archive if the cas_client isn't already installed
# and the CAS client isn't already installed
- name: Unpack cas-client source archive
  unarchive:
    src: "/tmp/cas-client.zip"
    dest: /tmp/
    remote_src: yes
  when: cas_client.stat.exists == False and cas_client.stat.exists == False

# Only do this if the cas_client isn't already installed
- name: Run autoreconf for CAS client
  command: "autoreconf -ivf"
  args:
    chdir: "/tmp/mod_auth_cas-master"
  when: cas_client.stat.exists == False

- name: Run configure for CAS client
  command: "./configure"
  args:
    chdir: "/tmp/mod_auth_cas-master"
  when: cas_client.stat.exists == False

- name: Run make for CAS client
  command: "make"
  args:
    chdir: "/tmp/mod_auth_cas-master"
  when: cas_client.stat.exists == False

- name: Ensure CAS cookie directory exists
  file:
    path: /var/cache/httpd/mod_auth_cas
    state: directory
    owner: apache
    group: apache
    mode: 0700

- name: Install CAS client
  command: "make install"
  args:
    chdir: "/tmp/mod_auth_cas-master"
  when: cas_client.stat.exists == False
  notify: reload httpd

- name: Setup Apache CAS config file
  template:
    src: dev-cas-client.conf.j2
    dest: /etc/httpd/conf.d/cas-client.conf
    mode: 0644
    owner: root
    group: root
  when: ("login6dev" in inventory_hostname)
  notify: reload httpd

- name: "Ensure php-fpm is set to start on boot"
  ansible.builtin.systemd:
    name: php-fpm
    state: started
    enabled: yes
