---
# handlers file for apache-tomcat
- name: reload ldconfig
  command: /sbin/ldconfig

- name: stop tomcat
  service: name=tomcat state=stopped

- name: start tomcat
  service: name=tomcat state=started

- name: restart tomcat
  service: name=tomcat state=restarted

